### ISSUE TITLE
Authentication section 

### ISSUE THREAD

**Issue by alexandrumatei36** [andreicatrina/Valuet-crypto#1]
# TODO

> Items to be fixed

- [x] authentication section `bg: linear-gradient(180deg, rgba(30, 17, 86, 0.9), rgba(14, 8, 55, 0.9));`
- [x] auth buttons `font-weight 700`
- [x] auth section shadow #0E0837 0px 12px 24px
- [x] auth section top padding 80px
- [x] auth inputs `border radius` & `border` when typing (just css)
- [x] no height for main-div
- [x] center child of `main-section` (100% height of body parent)
- [x] flex-direction instead of flex-flow
- [x] fix spacing between items using `margin` instead of gap
- [x] place title, inputs and buttons inside a `<form>` element
- [x] set action on Sign Up click
1. create js file and link it with the html file
2. attach `onClick` function on the Sign Up button (e.g console.log()). [Example here](https://www.w3schools.com/jsref/event_onclick.asp)
3. hide `sign-in-form` by adding `hidden` class to it [Example](https://www.w3schools.com/howto/howto_js_add_class.asp)
4. show sign-up form
